services:
  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - notes_db_container
  notes_db_container:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    expose: 
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
